############################# English ############################
[en]
languageName = "En"
title = "Blessing For VIPs"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Divine Details"
footer_menu_middle = "Cosmic Care"
footer_menu_right = "Ethereal Essentials"
footer_content = "Unlock blessings from the heavens â€“ Your subscription opens a portal to the world's sacred guardians, offering peace, prosperity, and protection."
# copyright
copyright = ""

